name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  lint_build_test:
    timeout-minutes: 10
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-22.04]
        node-version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Start containers
        run: |
          docker-compose -f "docker-compose.yml" up -d
          echo "Waiting for all container healthy..."
          sleep 30
          docker-compose logs
          echo "Containers ready."

      # Setup node with specific version
      - name: Install node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Receive yarn cached dependencies
        uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` ==> if: steps.yarn-cache.outputs.cache-hit != 'true'
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-Yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn --prefer-offline

      - name: Run lint, build, and test
        run: |
          yarn lint
          yarn build
          yarn test:detectOpenHandles

      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.yml" down
